### ISSUE TITLE
Somehow `CreateEC2LCWithoutKeyPair` doesn't actually work

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave-ecs-cloudformation#1]
Stack creation fails with `Parameter validation failed: parameter value for parameter name KeyName does not exist.`, when `KeyName` is empty.

**Comment by errordeveloper** [comment]
There doesn't seem to be a way to make it a required parameter, as parameters are inherently optional.

**Comment by 2opremio** [comment]
Can't you use a default value? You can check for the key name for the default value. If it is then you create a new key with that name, otherwise you use whatever key you were provided with.

**Comment by errordeveloper** [comment]
It doesn't look like _default key_ is a thing. Also, I am not able to find a way of fetching a list of keys; well, the UI gives you this handy search box... So, it looks like there is no way of enforcing this, and for some reason the `CreateEC2LCWithoutKeyPair` condition and the code path associated with it are a red herring. Basically, it looks like there is a bug in CF.

**Comment by errordeveloper** [comment]
Looks like setting `MinLength` gets it to fail early earlier, and you just have to select a key pair before you try creating the stack.
