### ISSUE TITLE
Add `WEAVE_NO_FASTDP=true` as an option

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/weave-ecs-cloudformation#3]
This is to work around weaveworks/weave#1577 until weave 1.4 is released.

**Comment by errordeveloper** [comment]
@fons, unlike #2 I cannot fix this without updating the AMI, unless I go for some nasty hack where I'd inject this variable into either `/etc/init/weave.conf` or one of the other scripts...

**Comment by 2opremio** [comment]
Weave 1.4 is going to be released very soon (end of the week I believe). So we won't need this unless the release is delayed.
